services:
  neo4j:
    image: neo4j:5.23-community
    container_name: neo4j
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"   # Browser
      - "${URI_PORT}:${URI_PORT}"   # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}   # user/pass
      - NEO4J_PLUGINS=["apoc"]  # install APOC plugin
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: